#!/usr/bin/env python3
"""Attacks on the new tests at 416a42e. Same machinery as harness.py."""
import os, sys
sys.dont_write_bytecode = True   # see the note in harness.py
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from harness import run_driver
from anchors import (INDEX_HTML, REPORT_PY, JS_TP_TILE, JS_EXEC_UNKNOWN, JS_CMP_UNKNOWN, JS_MD_UNKNOWN, JS_NOTES_UNKNOWN,
                 JS_BADGE, JS_TP_RETURN, JS_UNMODELLED_NOTE, PY_EXPLAIN, PY_NOTMOD_ROW)

JS_DECODE_ESTIMATE = "Math.round(computed.deviceBandwidth * 0.7 / (state.params * state.bytesPerParam))"  # borrowed 0.7 MBU, no PERF read
CAP_CARD = '<div class="reverse-card"><p class="label">Max concurrent @ 8K</p>'
FOOTER = '        canvas_obj.drawString(self.margin, 10*mm, "Generated by LLM VRAM Planner")\n'
SPEED_HINT_MARKUP = '<div id="throughput-output"></div>'

S = {}
# ---- numbers as words, units the regex does not list ----
S["N1 js: throughput tile adds 'Expect roughly forty tokens each second per user.'"] = [
    (INDEX_HTML, JS_TP_TILE, JS_TP_TILE + "<p class=\"sub\">Expect roughly forty tokens each second per user.</p>", 1)]
S["N2 js: exec summary adds a 'Speed per user: about forty tokens each second' row"] = [
    (INDEX_HTML, JS_EXEC_UNKNOWN, JS_EXEC_UNKNOWN + "    html += `<div class=\"exec-row\"><span class=\"exec-label\">Speed per user</span><span class=\"exec-value\">about forty tokens each second</span></div>`;\n", 1)]
S["N3 js: comparison card says 'not modelled (about forty tokens each second)'"] = [
    (INDEX_HTML, JS_CMP_UNKNOWN, JS_CMP_UNKNOWN.replace("not modelled<br>", "not modelled (about forty tokens each second)<br>"), 1)]
S["N4 js: markdown export adds '- Expected per-user speed: about forty tokens each second'"] = [
    (INDEX_HTML, JS_MD_UNKNOWN, JS_MD_UNKNOWN.replace("do not transfer.\\n`;", "do not transfer.\\n- Expected per-user speed: about forty tokens each second\\n`;"), 1)]
S["N5 js: notes say '…though about forty tokens each second per user is typical for this class'"] = [
    (INDEX_HTML, JS_NOTES_UNKNOWN, "    : 'Throughput is not modelled for this hardware: no measured utilisation is published for it, though about forty tokens each second per user is typical for this class. ';\n", 1)]
S["N6 js: the reason itself ends '(cards of this class manage about forty per user)'"] = [
    (INDEX_HTML, JS_UNMODELLED_NOTE, JS_UNMODELLED_NOTE.replace("which do not transfer</span>`;", "which do not transfer (cards of this class manage about forty per user)</span>`;"), 1)]
# ---- speed claims with no number ----
S["N7 js: throughput tile adds 'Fast enough for interactive chat on this card.'"] = [
    (INDEX_HTML, JS_TP_TILE, JS_TP_TILE + "<p class=\"sub\">Fast enough for interactive chat on this card.</p>", 1)]
S["N8 js: PCIe badge says 'not modelled, but expect about half the NVLink speed'"] = [
    (INDEX_HTML, JS_BADGE, JS_BADGE.replace("'PCIe — no NVLink; the speed cost is not modelled for this hardware'", "'PCIe — no NVLink; not modelled, but expect about half the NVLink speed'"), 1)]
S["N9 js: exec summary row reads 'Not modelled — but comfortably fast for chat'"] = [
    (INDEX_HTML, JS_EXEC_UNKNOWN, JS_EXEC_UNKNOWN.replace("Not modelled <span", "Not modelled — but comfortably fast for chat <span"), 1)]
# ---- figures in attributes / tooltips ----
S["N10 js: tooltip on the 'Not modelled' value: title=\"Rough estimate: ~<borrowed> t/s per user\""] = [
    (INDEX_HTML, JS_TP_TILE, JS_TP_TILE.replace("<p class=\"value\">Not modelled</p>", f"<p class=\"value\" title=\"Rough estimate: ~${{{JS_DECODE_ESTIMATE}}} t/s per user\">Not modelled</p>"), 1)]
S["N10b js (control): the same tooltip spelled 'tok/s'"] = [
    (INDEX_HTML, JS_TP_TILE, JS_TP_TILE.replace("<p class=\"value\">Not modelled</p>", f"<p class=\"value\" title=\"Rough estimate: ~${{{JS_DECODE_ESTIMATE}}} tok/s per user\">Not modelled</p>"), 1)]
S["N11 js: data attribute on the exec row: data-estimate=\"<borrowed>\""] = [
    (INDEX_HTML, JS_EXEC_UNKNOWN, JS_EXEC_UNKNOWN.replace("<div class=\"exec-row\"><span class=\"exec-label\">Speed and server throughput</span>", f"<div class=\"exec-row\" data-estimate=\"${{{JS_DECODE_ESTIMATE}}}\" title=\"about ${{{JS_DECODE_ESTIMATE}}} per user\"><span class=\"exec-label\">Speed and server throughput</span>"), 1)]
# ---- writes the harness never captures ----
S["N12 js: figure written with textContent to a side element (#speed-hint) for the unknown card"] = [
    (INDEX_HTML, SPEED_HINT_MARKUP, "<div id=\"throughput-output\"></div><div id=\"speed-hint\" style=\"font-size:11px\"></div>", 1),
    (INDEX_HTML, JS_TP_RETURN, JS_TP_RETURN.replace("    return;\n", f"    const hint = document.getElementById('speed-hint'); if (hint) hint.textContent = 'Rough decode ~' + {JS_DECODE_ESTIMATE} + ' tok/s per user';\n    return;\n"), 1)]
S["N13 js: tooltip set as a property on the throughput panel element (.title = '~<borrowed> tok/s')"] = [
    (INDEX_HTML, JS_TP_RETURN, JS_TP_RETURN.replace("    return;\n", f"    document.getElementById('throughput-output').title = 'roughly ~' + {JS_DECODE_ESTIMATE} + ' tok/s per user';\n    return;\n"), 1)]
# ---- a borrowed-constant figure shown for every card, in an element held byte-identical ----
S["N14 js: capacity panel gains a 'Rough decode ~<borrowed> t/s' card for every card (known and unknown alike)"] = [
    (INDEX_HTML, CAP_CARD, f"<div class=\"reverse-card\"><p class=\"label\">Rough decode</p><p class=\"value\">~${{{JS_DECODE_ESTIMATE}}} t/s</p><p class=\"sub\">bandwidth × 70% over weights</p></div>" + CAP_CARD, 1)]
S["N14b js (control): the same card spelled 'tok/s'"] = [
    (INDEX_HTML, CAP_CARD, f"<div class=\"reverse-card\"><p class=\"label\">Rough decode</p><p class=\"value\">~${{{JS_DECODE_ESTIMATE}}} tok/s</p><p class=\"sub\">bandwidth × 70% over weights</p></div>" + CAP_CARD, 1)]
# ---- digits under an unlisted unit (controls: the digit rule should catch these) ----
S["N15 js (control): exec summary adds '~<borrowed×60> tokens per minute'"] = [
    (INDEX_HTML, JS_EXEC_UNKNOWN, JS_EXEC_UNKNOWN + f"    html += `<div class=\"exec-row\"><span class=\"exec-label\">Speed per user</span><span class=\"exec-value\">~${{{JS_DECODE_ESTIMATE} * 60}} tokens per minute</span></div>`;\n", 1)]
S["N16 js (control): throughput tile adds 'first token after about 4.5 seconds'"] = [
    (INDEX_HTML, JS_TP_TILE, JS_TP_TILE + "<p class=\"sub\">First token after about 4.5 seconds.</p>", 1)]
S["N17 js: throughput tile adds 'first token after about four seconds'"] = [
    (INDEX_HTML, JS_TP_TILE, JS_TP_TILE + "<p class=\"sub\">First token after about four seconds.</p>", 1)]

# ---- PDF ----
S["Q1 py: figure paragraph wrapped in KeepTogether (spy-blind container)"] = [
    (REPORT_PY, PY_EXPLAIN, PY_EXPLAIN + "            story.append(KeepTogether([Paragraph(f\"Rough decode estimate: ~{c['single_tok'] or 0} tokens/sec per user\", self.styles[\"Small\"])]))\n", 1)]
S["Q2 py: figure drawn on the canvas footer for the unknown card"] = [
    (REPORT_PY, FOOTER, "        canvas_obj.drawString(self.margin, 10*mm, \"Generated by LLM VRAM Planner\" + (\"\" if self.comp[\"throughput_modelled\"] else f\" — rough decode ~{self.comp['single_tok'] or 0} tok/s per user\"))\n", 1)]
S["Q3 py: explanation ends 'Expect roughly forty tokens each second per user.'"] = [
    (REPORT_PY, "                \"depend on them.\",\n                self.styles[\"Small\"]\n", "                \"depend on them. Expect roughly forty tokens each second per user.\",\n                self.styles[\"Small\"]\n", 1)]
S["Q4 py: throughput table gains a row 'Rough per-user decode: about forty tokens each second'"] = [
    (REPORT_PY, PY_NOTMOD_ROW, PY_NOTMOD_ROW + "                [\"Rough per-user decode\", \"about forty tokens each second\"],\n", 1)]
S["Q5 py: notes gain 'Cards of this class typically manage about forty tokens each second per user.'"] = [
    (REPORT_PY, "        notes.append(\"VRAM estimates include ~1.5 GB CUDA context overhead per device.\")\n",
     "        notes.append(\"VRAM estimates include ~1.5 GB CUDA context overhead per device.\")\n        if not c[\"throughput_modelled\"]:\n            notes.append(\"Cards of this class typically manage about forty tokens each second per user.\")\n", 1)]
S["Q6 py: notes gain 'This card should be fast enough for interactive chat.'"] = [
    (REPORT_PY, "        notes.append(\"VRAM estimates include ~1.5 GB CUDA context overhead per device.\")\n",
     "        notes.append(\"VRAM estimates include ~1.5 GB CUDA context overhead per device.\")\n        if not c[\"throughput_modelled\"]:\n            notes.append(\"This card should be fast enough for interactive chat.\")\n", 1)]
S["Q7 py (control): throughput table row '~<n> tokens per minute'"] = [
    (REPORT_PY, PY_NOTMOD_ROW, PY_NOTMOD_ROW + "                [\"Rough per-user decode\", f\"~{(c['single_tok'] or 12) * 60} tokens per minute\"],\n", 1)]
S["Q8 py (control): figure in a list-of-flowables table cell"] = [
    (REPORT_PY, PY_NOTMOD_ROW, PY_NOTMOD_ROW + "                [\"Rough per-user decode\", [Paragraph(f\"~{c['single_tok'] or 0} tokens/sec\", self.styles[\"Small\"])]],\n", 1)]
S["Q9 py (control): figure in a nested table cell"] = [
    (REPORT_PY, PY_NOTMOD_ROW, PY_NOTMOD_ROW + "                [\"Rough per-user decode\", Table([[f\"~{c['single_tok'] or 0} tokens/sec\"]])],\n", 1)]
S["Q10 py: 'Not modelled' cell reads 'Not modelled (fast enough for chat)'"] = [
    (REPORT_PY, PY_NOTMOD_ROW, "                [\"Throughput and TTFT\", \"Not modelled (fast enough for chat)\"],\n", 1)]

if __name__ == "__main__":
    run_driver(S)
