#!/usr/bin/env python3
"""Regenerate the GPU_TABLE blocks inlined in index.html and generate_report.py
from data/gpus.json.

data/gpus.json is the contributor-facing source of truth for the GPU catalog.
index.html (which must stay fully self-contained and loadable from file://,
so it cannot fetch the JSON at runtime) and generate_report.py each carry
their own inline copy, generated by this script between matching
'GPU_TABLE:BEGIN' / 'GPU_TABLE:END' marker comments.

This is a contributor convenience, not a build step: the committed
index.html and generate_report.py are always complete and correct on their
own. Running this script against an unedited data/gpus.json is a no-op —
tests/parity.test.py asserts both inline copies already match the JSON, so a
diff here means someone edited a generated block by hand instead of the
source, or edited the JSON and forgot to re-run this script.

Usage:
    python3 tools/sync_data.py
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BEGIN_TAG = "GPU_TABLE:BEGIN"
END_TAG = "GPU_TABLE:END"

# Marker-line regex shared by both files: match from whatever comment syntax
# wraps BEGIN_TAG through whatever comment syntax wraps END_TAG, so the same
# replacement logic works for index.html's /* ... */ and generate_report.py's
# # ... without knowing which file it's touching.
BLOCK_RE = re.compile(
    r"^.*" + re.escape(BEGIN_TAG) + r".*$\n(?:.*\n)*?^.*" + re.escape(END_TAG) + r".*$",
    re.MULTILINE,
)


def load_gpus():
    with open(os.path.join(ROOT, "data", "gpus.json")) as f:
        return json.load(f)["data"]


def js_num(v):
    # JSON and JS share number syntax, so json.dumps already renders a Python
    # int/float the way a JS numeric literal needs (16, 0.76, 12.3, ...).
    return json.dumps(v)


def js_str(v):
    # Single-quoted, matching MODEL_PRESETS/WORKLOAD_PROFILES style elsewhere
    # in index.html's inline script.
    return "'" + v.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render_js_block(gpus):
    lines = [
        f"/* {BEGIN_TAG} — generated by tools/sync_data.py from data/gpus.json. "
        "Do not hand-edit; edit the JSON and re-run the script. */",
        "const GPU_TABLE = {",
    ]
    for key, g in gpus.items():
        row = ", ".join([
            f"gb:{js_num(g['gb'])}", f"bw:{js_num(g['bw'])}",
            f"hyper:{js_num(g['hyper'])}", f"spec:{js_num(g['spec'])}",
            f"spot:{js_num(g['spot'])}", f"tflops:{js_num(g['tflops'])}",
            f"name:{js_str(g['name'])}",
        ])
        lines.append(f"  {js_str(key)}: {{ {row} }},")
    lines.append("};")
    lines.append(f"/* {END_TAG} */")
    return "\n".join(lines) + "\n"


def render_py_block(gpus):
    lines = [
        f"# {BEGIN_TAG} — generated by tools/sync_data.py from data/gpus.json. "
        "Do not hand-edit; edit the JSON and re-run the script.",
        "GPUS = {",
    ]
    for key, g in gpus.items():
        row = ", ".join([
            f'"gb":{json.dumps(g["gb"])}', f'"bw":{json.dumps(g["bw"])}',
            f'"hyper":{json.dumps(g["hyper"])}', f'"spec":{json.dumps(g["spec"])}',
            f'"spot":{json.dumps(g["spot"])}', f'"tflops":{json.dumps(g["tflops"])}',
            f'"name":{json.dumps(g["name"])}',
        ])
        lines.append(f'    "{key}": {{{row}}},')
    lines.append("}")
    lines.append(f"# {END_TAG}")
    return "\n".join(lines) + "\n"


def sync_file(path, new_block):
    with open(path) as f:
        old_text = f.read()
    if not BLOCK_RE.search(old_text):
        raise SystemExit(
            f"{path}: no {BEGIN_TAG} ... {END_TAG} block found — "
            "has the marker comment been removed or renamed?"
        )
    new_text = BLOCK_RE.sub(lambda m: new_block.rstrip("\n"), old_text, count=1)
    rel = os.path.relpath(path, ROOT)
    if new_text == old_text:
        print(f"{rel}: unchanged")
        return False
    with open(path, "w") as f:
        f.write(new_text)
    print(f"{rel}: updated")
    return True


def main():
    gpus = load_gpus()
    changed = False
    changed |= sync_file(os.path.join(ROOT, "index.html"), render_js_block(gpus))
    changed |= sync_file(os.path.join(ROOT, "generate_report.py"), render_py_block(gpus))
    if changed:
        print("Re-run tests/run.sh before committing.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
