#!/usr/bin/env python3
"""Regenerate the data blocks inlined in index.html and generate_report.py
from the contributor-facing JSON files.

data/gpus.json and benchmarks/data.json are the sources of truth. index.html
(which must stay fully self-contained and loadable from file://, so it cannot
fetch a sibling JSON at runtime) and generate_report.py each carry their own
inline copy, generated by this script between matching '<TAG>:BEGIN' /
'<TAG>:END' marker comments.

Blocks generated, one entry per (file, tag) pair in BLOCKS below:
    index.html         GPU_TABLE       <- data/gpus.json
    generate_report.py GPU_TABLE       <- data/gpus.json
    index.html         BENCHMARK_DATA  <- benchmarks/data.json

This is a contributor convenience, not a build step: the committed
index.html and generate_report.py are always complete and correct on their
own. Running this script against an unedited data/gpus.json is a no-op —
tests/parity.test.py asserts both inline copies already match the JSON, so a
diff here means someone edited a generated block by hand instead of the
source, or edited the JSON and forgot to re-run this script.

Usage:
    python3 tools/sync_data.py
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TAGS = ("GPU_TABLE", "BENCHMARK_DATA")


# A marker line opens with a comment: /* for index.html, # for the Python.
# Requiring that is what stops a *value* inside the block from being mistaken
# for its own end marker — a benchmark note discussing this tool by name is
# ordinary contributor prose, and a row is always indented data, never a
# comment. Without it the non-greedy match below ends at the poisoned row and
# the replacement splices a new block into the middle of the old one, leaving
# an orphaned `};` that stops the whole inline script from parsing.
COMMENT_OPEN = r"^[ \t]*(?:/\*|#)[^\n]*"


def block_re(tag):
    """Match from the comment line carrying <tag>:BEGIN through the comment line
    carrying <tag>:END, whatever comment syntax wraps them — so one replacement
    path serves index.html's /* ... */ and generate_report.py's # ... alike. Not
    greedy: two tagged blocks in one file must not swallow each other."""
    return re.compile(
        COMMENT_OPEN + re.escape(tag + ":BEGIN") + r".*$\n(?:.*\n)*?"
        + COMMENT_OPEN + re.escape(tag + ":END") + r".*$",
        re.MULTILINE,
    )


# Compiled once at import, since every tag is known here and nowhere else.
BLOCK_RES = {tag: block_re(tag) for tag in TAGS}


def load_gpus():
    with open(os.path.join(ROOT, "data", "gpus.json")) as f:
        return json.load(f)["data"]


def load_benchmarks():
    with open(os.path.join(ROOT, "benchmarks", "data.json")) as f:
        return json.load(f)["data"]


# Field order per table, and the contract each renderer emits. Optional fields
# are written only on the rows that carry them: `default` marks exactly one
# card, and a `default: false` on the other eleven would be a value nobody
# wrote in data/gpus.json. Same for `estimated`, which benchmarks/data.json
# documents as "omit or false for real measurements".
GPU_FIELDS = ("gb", "bw", "hyper", "spec", "spot", "tflops", "name",
              "vendor", "devices", "form", "caps")
GPU_OPTIONAL = ("default",)

# Every field benchmarks/data.json documents. The inline copy carried four of
# them — tokS, src, note, prec — so `mode` fell back to 'batch' for entries
# measured single-stream, and `estimated` never reached the badge that renders
# it. date/url are what the panel's provenance line is owed next.
BENCH_FIELDS = ("tokS", "mode", "src", "note", "prec", "date", "url")
BENCH_OPTIONAL = ("estimated",)

# A JS identifier, i.e. an object key that needs no quotes.
IDENT_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")

# Belt as well as braces. The comment-line requirement above means a marker
# inside a value can no longer break the replacement, but a value containing
# one is still confusing to read and a hostage to the next change in this file,
# so it is refused outright, naming the row and field that carry it.
MARKER_RE = re.compile("(?:" + "|".join(re.escape(t) for t in TAGS) + "):(?:BEGIN|END)")


def js_str(v):
    """Single-quoted, matching MODEL_PRESETS/WORKLOAD_PROFILES style elsewhere
    in index.html's inline script.

    Escaping only \\ and ' was enough while every string here was a GPU name
    this repo writes. Benchmark notes and source names are contributor free
    text, and the block they land in is inside <script> in an HTML file: a note
    containing </script> would end the script tag mid-literal and take the rest
    of the tool with it. The HTML parser sees that sequence before JavaScript
    does, so it has to be broken here — <\\/ is the same string to JS and
    nothing to the parser. Line terminators are escaped for the same class of
    reason: a raw newline is a syntax error inside a single-quoted literal, and
    U+2028/9 are line terminators to JS but not to Python.
    """
    out = v.replace("\\", "\\\\").replace("'", "\\'").replace("</", "<\\/")
    # Every C0 control, not just the line terminators. A raw NUL is the one that
    # bites without any of them: the HTML tokenizer rewrites it to U+FFFD before
    # JavaScript ever sees the literal, so the note a contributor wrote is not
    # the note the page shows — silently, and invisibly to a Node-based test,
    # which never tokenises HTML. U+2028/9 end a line to JS but not to Python.
    return "'" + "".join(
        ch if (ch >= " " and ch not in "\u2028\u2029") else "\\u%04x" % ord(ch)
        for ch in out
    ) + "'"


def js_key(k):
    return k if IDENT_RE.match(k) else js_str(k)


def js_value(v):
    """Render a JSON value as a JavaScript literal.

    Per-type rather than json.dumps because the generated block follows the
    surrounding file's style — single-quoted strings, unquoted keys — and
    because the row schema now nests (caps: { fp8: true }) and is expected to
    hold arrays (aliases) before v1.1 is done. bool is tested before int on
    purpose: bool is an int subclass in Python, so the other order renders
    true as 1.
    """
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        # JSON and JS share number syntax, so json.dumps already renders a
        # Python int/float the way a JS numeric literal needs.
        return json.dumps(v)
    if isinstance(v, str):
        return js_str(v)
    if isinstance(v, list):
        return "[" + ", ".join(js_value(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{ " + ", ".join(f"{js_key(k)}: {js_value(x)}" for k, x in v.items()) + " }"
    raise SystemExit(f"data/gpus.json: no JS rendering for {type(v).__name__}: {v!r}")


def py_value(v):
    """Render a JSON value as a Python literal.

    json.dumps is not usable here as-is: it emits true/false, which are not
    Python. Everything else it gets right, but a dict of JSON values needs
    the same recursion the JS side has, so both sides are written the same way
    and stay easy to compare.
    """
    if isinstance(v, bool):
        return "True" if v else "False"
    if isinstance(v, (int, float, str)):
        return json.dumps(v)
    if isinstance(v, list):
        return "[" + ", ".join(py_value(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ", ".join(f"{json.dumps(k)}: {py_value(x)}" for k, x in v.items()) + "}"
    raise SystemExit(f"data/gpus.json: no Python rendering for {type(v).__name__}: {v!r}")


def row_fields(source, row_key, row, fields, optional, value, key, sep):
    """Render one row's fields, in one place, for every renderer.

    value/key render a single value and a single field name in the target
    language; sep joins the pairs. Everything else about a row — which fields,
    in what order, and which may be absent — is decided by the caller's field
    lists, so two renderers over the same table cannot disagree about them.
    """
    missing = [f for f in fields if f not in row]
    if missing:
        raise SystemExit(
            f"{source}: row {row_key!r} is missing required field(s) {missing}. "
            f"Every row carries {list(fields)}; only {list(optional)} may be absent."
        )
    names = list(fields) + [f for f in optional if f in row]
    for f in names:
        found = MARKER_RE.search(str(row[f]))
        if found:
            raise SystemExit(
                f"{source}: row {row_key!r} field {f!r} contains {found.group(0)!r}, "
                "which is the text this tool uses to find the block it generates. "
                "Reword it — the generated file would be ambiguous about where "
                "its own data ends."
            )
    return sep.join(f"{key(f)}{value(row[f])}" for f in names)


def js_block(tag, source, var, rows, fields, optional):
    """A generated `const <var> = { ... };` block, marker comments included."""
    lines = [
        f"/* {tag}:BEGIN — generated by tools/sync_data.py from {source}. "
        "Do not hand-edit; edit the JSON and re-run the script. */",
        f"const {var} = {{",
    ]
    for key, row in rows.items():
        body = row_fields(source, key, row, fields, optional,
                          js_value, lambda f: f"{f}:", ", ")
        lines.append(f"  {js_str(key)}: {{ {body} }},")
    lines.append("};")
    lines.append(f"/* {tag}:END */")
    return "\n".join(lines) + "\n"


def render_gpu_js(gpus):
    return js_block("GPU_TABLE", "data/gpus.json", "GPU_TABLE",
                    gpus, GPU_FIELDS, GPU_OPTIONAL)


def render_benchmark_js(bench):
    return js_block("BENCHMARK_DATA", "benchmarks/data.json", "BENCHMARK_DATA",
                    bench, BENCH_FIELDS, BENCH_OPTIONAL)


def render_gpu_py(gpus):
    source = "data/gpus.json"
    lines = [
        f"# GPU_TABLE:BEGIN — generated by tools/sync_data.py from {source}. "
        "Do not hand-edit; edit the JSON and re-run the script.",
        "GPUS = {",
    ]
    for key, g in gpus.items():
        body = row_fields(source, key, g, GPU_FIELDS, GPU_OPTIONAL,
                          py_value, lambda f: f'"{f}":', ",")
        lines.append(f'    "{key}": {{{body}}},')
    lines.append("}")
    lines.append("# GPU_TABLE:END")
    return "\n".join(lines) + "\n"


# Every generated block: which file it lives in, which marker pair delimits it,
# and what renders it. generate_report.py has no benchmark panel, so it carries
# no BENCHMARK_DATA block — the report generator does not compare against
# published numbers.
BLOCKS = (
    ("index.html", "GPU_TABLE", render_gpu_js, load_gpus),
    ("generate_report.py", "GPU_TABLE", render_gpu_py, load_gpus),
    ("index.html", "BENCHMARK_DATA", render_benchmark_js, load_benchmarks),
)


def sync_file(rel, tag, new_block):
    path = os.path.join(ROOT, rel)
    with open(path) as f:
        old_text = f.read()
    pattern = BLOCK_RES[tag]
    if not pattern.search(old_text):
        raise SystemExit(
            f"{rel}: no {tag}:BEGIN ... {tag}:END block found — "
            "has the marker comment been removed or renamed?"
        )
    # count=1: a second block carrying the same tag in one file would be a
    # copy-paste of the first, and rewriting both would hide it.
    new_text = pattern.sub(lambda m: new_block.rstrip("\n"), old_text, count=1)
    if new_text == old_text:
        print(f"{rel}: {tag} unchanged")
        return False
    with open(path, "w") as f:
        f.write(new_text)
    print(f"{rel}: {tag} updated")
    return True


def main():
    changed = False
    for rel, tag, renderer, loader in BLOCKS:
        changed |= sync_file(rel, tag, renderer(loader()))
    if changed:
        print("Re-run tests/run.sh before committing.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
