#!/usr/bin/env python3
"""Regenerate the GPU_TABLE blocks inlined in index.html and generate_report.py
from data/gpus.json.

data/gpus.json is the contributor-facing source of truth for the GPU catalog.
index.html (which must stay fully self-contained and loadable from file://,
so it cannot fetch the JSON at runtime) and generate_report.py each carry
their own inline copy, generated by this script between matching
'GPU_TABLE:BEGIN' / 'GPU_TABLE:END' marker comments.

This is a contributor convenience, not a build step: the committed
index.html and generate_report.py are always complete and correct on their
own. Running this script against an unedited data/gpus.json is a no-op —
tests/parity.test.py asserts both inline copies already match the JSON, so a
diff here means someone edited a generated block by hand instead of the
source, or edited the JSON and forgot to re-run this script.

Usage:
    python3 tools/sync_data.py
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BEGIN_TAG = "GPU_TABLE:BEGIN"
END_TAG = "GPU_TABLE:END"

# Marker-line regex shared by both files: match from whatever comment syntax
# wraps BEGIN_TAG through whatever comment syntax wraps END_TAG, so the same
# replacement logic works for index.html's /* ... */ and generate_report.py's
# # ... without knowing which file it's touching.
BLOCK_RE = re.compile(
    r"^.*" + re.escape(BEGIN_TAG) + r".*$\n(?:.*\n)*?^.*" + re.escape(END_TAG) + r".*$",
    re.MULTILINE,
)


def load_gpus():
    with open(os.path.join(ROOT, "data", "gpus.json")) as f:
        return json.load(f)["data"]


# Field order for both generated blocks, and the contract each renderer emits.
# Optional fields are written only on the rows that carry them: `default` marks
# exactly one card, and a `default: false` on the other eleven would be a value
# nobody wrote in data/gpus.json.
FIELDS = ("gb", "bw", "hyper", "spec", "spot", "tflops", "name",
          "vendor", "devices", "form", "caps")
OPTIONAL_FIELDS = ("default",)

# A JS identifier, i.e. an object key that needs no quotes.
IDENT_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def js_str(v):
    # Single-quoted, matching MODEL_PRESETS/WORKLOAD_PROFILES style elsewhere
    # in index.html's inline script.
    return "'" + v.replace("\\", "\\\\").replace("'", "\\'") + "'"


def js_key(k):
    return k if IDENT_RE.match(k) else js_str(k)


def js_value(v):
    """Render a JSON value as a JavaScript literal.

    Per-type rather than json.dumps because the generated block follows the
    surrounding file's style — single-quoted strings, unquoted keys — and
    because the row schema now nests (caps: { fp8: true }) and is expected to
    hold arrays (aliases) before v1.1 is done. bool is tested before int on
    purpose: bool is an int subclass in Python, so the other order renders
    true as 1.
    """
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        # JSON and JS share number syntax, so json.dumps already renders a
        # Python int/float the way a JS numeric literal needs.
        return json.dumps(v)
    if isinstance(v, str):
        return js_str(v)
    if isinstance(v, list):
        return "[" + ", ".join(js_value(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{ " + ", ".join(f"{js_key(k)}: {js_value(x)}" for k, x in v.items()) + " }"
    raise SystemExit(f"data/gpus.json: no JS rendering for {type(v).__name__}: {v!r}")


def py_value(v):
    """Render a JSON value as a Python literal.

    json.dumps is not usable here as-is: it emits true/false, which are not
    Python. Everything else it gets right, but a dict of JSON values needs
    the same recursion the JS side has, so both sides are written the same way
    and stay easy to compare.
    """
    if isinstance(v, bool):
        return "True" if v else "False"
    if isinstance(v, (int, float, str)):
        return json.dumps(v)
    if isinstance(v, list):
        return "[" + ", ".join(py_value(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ", ".join(f"{json.dumps(k)}: {py_value(x)}" for k, x in v.items()) + "}"
    raise SystemExit(f"data/gpus.json: no Python rendering for {type(v).__name__}: {v!r}")


def row_fields(gpu_key, gpu, value, key, sep):
    """The one field list both renderers walk, so they cannot diverge.

    value/key render a single value and a single field name in the target
    language; sep joins the pairs. Everything else about a row — which fields,
    in what order, and which may be absent — is decided here, once.
    """
    missing = [f for f in FIELDS if f not in gpu]
    if missing:
        raise SystemExit(
            f"data/gpus.json: row {gpu_key!r} is missing required field(s) {missing}. "
            "Every row carries every field in FIELDS; only "
            f"{list(OPTIONAL_FIELDS)} may be absent."
        )
    names = list(FIELDS) + [f for f in OPTIONAL_FIELDS if f in gpu]
    return sep.join(f"{key(f)}{value(gpu[f])}" for f in names)


def render_js_block(gpus):
    lines = [
        f"/* {BEGIN_TAG} — generated by tools/sync_data.py from data/gpus.json. "
        "Do not hand-edit; edit the JSON and re-run the script. */",
        "const GPU_TABLE = {",
    ]
    for key, g in gpus.items():
        row = row_fields(key, g, js_value, lambda f: f"{f}:", ", ")
        lines.append(f"  {js_str(key)}: {{ {row} }},")
    lines.append("};")
    lines.append(f"/* {END_TAG} */")
    return "\n".join(lines) + "\n"


def render_py_block(gpus):
    lines = [
        f"# {BEGIN_TAG} — generated by tools/sync_data.py from data/gpus.json. "
        "Do not hand-edit; edit the JSON and re-run the script.",
        "GPUS = {",
    ]
    for key, g in gpus.items():
        row = row_fields(key, g, py_value, lambda f: f'"{f}":', ",")
        lines.append(f'    "{key}": {{{row}}},')
    lines.append("}")
    lines.append(f"# {END_TAG}")
    return "\n".join(lines) + "\n"


def sync_file(path, new_block):
    with open(path) as f:
        old_text = f.read()
    if not BLOCK_RE.search(old_text):
        raise SystemExit(
            f"{path}: no {BEGIN_TAG} ... {END_TAG} block found — "
            "has the marker comment been removed or renamed?"
        )
    new_text = BLOCK_RE.sub(lambda m: new_block.rstrip("\n"), old_text, count=1)
    rel = os.path.relpath(path, ROOT)
    if new_text == old_text:
        print(f"{rel}: unchanged")
        return False
    with open(path, "w") as f:
        f.write(new_text)
    print(f"{rel}: updated")
    return True


def main():
    gpus = load_gpus()
    changed = False
    changed |= sync_file(os.path.join(ROOT, "index.html"), render_js_block(gpus))
    changed |= sync_file(os.path.join(ROOT, "generate_report.py"), render_py_block(gpus))
    if changed:
        print("Re-run tests/run.sh before committing.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
